---
abstract: 'A simple to use POE SMTP Server.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-SimpleSMTP
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Carp: 0
  Email::Address: 1.886
  Email::MessageID: 1.4
  Email::Simple: 1.998
  Email::Simple::Creator: 1.41
  POE: 1.0002
  POE::Component::Client::DNS: 0.99
  POE::Component::Client::SMTP: 0.18
  POE::Component::Pluggable: 0.03
  POE::Filter::Line: 0
  POE::Filter::Transparent::SMTP: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  POSIX: 0
  Socket: 0
  Storable: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.22
